# Template C++ Application

# This template allows you to validate your C++ application.
# The workflow allows running tests and code linting on the default branch.


image: gcc:10.2


pipelines:
  default:
    - parallel:
        - step:
            name: Build and Run ex00
            script:
              - cd ./ex00
              - make
              - ./megaphone | diff - <(echo "* LOUD AND UNBEARABLE FEEDBACK NOISE *")
              - ./megaphone hola | diff - <(echo "HOLA ")
              - ./megaphone que tal? | diff - <(echo "QUE TAL? ")
              - ./megaphone EsTo AlTeRnA MAYUSCULAS y minusculas | diff - <(echo "ESTO ALTERNA MAYUSCULAS Y MINUSCULAS ")
              - ./megaphone "ahora, todo junto!" | diff - <(echo "AHORA, TODO JUNTO! ")
              - make fclean
        - step:
            name: Build and Run ex01
            script:
              - cd ./ex01
              - make
              - make fclean
        - step:
            name: Build and Run ex02
            script:
              - cd ./ex02
              - make
              - ./account > out.log
              - cat out.log
              - diff <(cut -c 18- out.log) <(cut -c 18- 19920104_091532.log)
              - make fclean
